### ISSUE TITLE
Can't verify token - "The provided Algorithm doesn't match the one used to sign the JWT."  [godot 4]

### ISSUE THREAD

**Issue by ababen1** [fenix-hub/godot-engine.jwt#17] opened 2023-11-12 13:36 UTC
Hello, I followed the readme's insturctions on creating HS256 token and created these functions:

```
static func dict_to_jwt(data: Dictionary = {}) -> String:
	var secret: String = JWTAlgorithmBuilder.random_secret()
	var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.HS256(secret)
	var jwt_builder: JWTBuilder = JWT.create() \
	.with_expires_at(Time.get_unix_time_from_system()) \
	.with_issuer("Godot") \
	.with_payload(data)
	var jwt: String = jwt_builder.sign(jwt_algorithm)
	return jwt

static func verify_jwt(jwt: String, secret: String) -> bool:
	var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.HS256(secret)
	var jwt_verifier: JWTVerifier = JWT.require(jwt_algorithm) \
		.build() # Reusable Verifier
	var is_valid = jwt_verifier.verify(jwt) == JWTVerifier.JWTExceptions.OK
	if !is_valid:
		print(jwt_verifier.exception)
	return is_valid

```

But I get an error in `verify_jwt` saying `The provided Algorithm doesn't match the one used to sign the JWT.`
even though I used the same algorithem
Godot version: v4.1.3.stable.official [f06b6836a]
I used the code from the main godot 4 branch

**Comment by chrisl8** [comment] 2023-11-12 17:51
I noticed two things about this line:
`.with_expires_at(Time.get_unix_time_from_system())`

1. `Time.get_unix_time_from_system()` returns a float, but `expires_at` needs an int.
2. This line is telling it to expire immediately, because it adds the current time as the expires time.

Could either of those be the issue?


In case it helps, here is the GDScript code I use which works as an example
```
func generate_jwt(secret: String, player_uuid: String) -> String:
	var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.HS256(secret)
	var jwt_builder: JWTBuilder = (
		JWT
		. create()
		. with_issued_at(int(Time.get_unix_time_from_system()))
		. with_expires_at(int(Time.get_unix_time_from_system()) + 60 * 60 * 24 * 365)
		. with_issuer("Space Game")
		. with_payload({"uuid": player_uuid})
	)
	var jwt: String = jwt_builder.sign(jwt_algorithm)
	return jwt


func validate_and_decode_jwt(secret: String, jwt: String) -> Dictionary:
	var content: Dictionary = {}
	var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.HS256(secret)
	var jwt_verifier: JWTVerifier = JWT.require(jwt_algorithm).build()  # Reusable Verifier
	if jwt_verifier.verify(jwt) == JWTVerifier.JWTExceptions.OK:
		var jwt_decoder: JWTDecoder = JWT.decode(jwt)
		content = jwt_decoder.get_claims()
	else:
		printerr(jwt_verifier.exception)
	return content
```

The player_uuid is not important, I just included it as an example of payload data.

**Comment by ababen1** [comment] 2023-11-12 18:14
Yes this is helpful, thank you :)
You're right about the expiration time, I got the validation working now, the error message was just misleading.

**Comment by fenix-hub** [comment] 2023-11-13 07:44
@chrisl8 Thank you very much for replying to the issue.
If it is solved, I'll close this one making sure to fix the error message for this case.

**Closed as completed** 2023-11-15 08:26 UTC
Labels: bug

**Comment by chrisl8** [comment] 2023-11-17 17:11
I think that the issue is here:
https://github.com/fenix-hub/godot-engine.jwt/blob/db7df550efdbf60c0241f6698826232ada0a6646/addons/jwt/src/JWTVerifier.gd#L29-L31

The `verify_signature` function has very similar exception text to the `verify_algorithm` text.

Perhaps it should indicate that the signature does not match instead of the algorithm.
